### ISSUE TITLE
关于使用自己数据集进行训练出错

### ISSUE THREAD

**Issue by streetlime** [Lornatang/CRNN-PyTorch#1]
使用自己训练集并且将config文件修改为train模式后 使用python train.py 命令出现 如下报错:
Load all datasets successfully.
Build CRNN model successfully.
Define all loss functions successfully.
Define all optimizer functions successfully.
Check whether the pretrained model is restored...
* Acc: 0.00%
Traceback (most recent call last):
  File "train.py", line 364, in <module>
    main()
  File "train.py", line 85, in main
    acc = validate(model, test_dataloader, epoch, writer, "Valid")
  File "train.py", line 291, in validate
    raise ValueError("Unsupported mode, please use `valid` or `test`.")
ValueError: Unsupported mode, please use `valid` or `test`.

**Comment by Lornatang** [comment]
是我这边写错了一个常量，现在可以了

**Comment by streetlime** [comment]
> 是我这边写错了一个常量，现在可以了

请问开始训练后acc一直是0% 是数据集的问题无法收敛 还是迭代次数过少呢 我epoch使用了200次 然后用last.pth.tar进行预测精度为0 数据集是直接使用人工生成的纯字符数据集

**Comment by Lornatang** [comment]
每个Epoch有多少个批次数据？

**Comment by streetlime** [comment]
> 每个Epoch有多少个批次数据？

真的不好意思 刚刚只是进行了测试 config文件里的其他东西我都没改, 好像train只有10张 valid也只有十张 就是能迭代能test的话应该就没有问题了是吗, 那能请教一下类似我这种相对简单的不定长数字加"-"符号的数据集大概需要多少epoch和数据集的数量呢

**Comment by Lornatang** [comment]
按照经验来说，一百万张图像+32次Epoch

**Comment by streetlime** [comment]
> 

好的好的 谢谢回复啦 辛苦

**Comment by Lornatang** [comment]
谢谢！一起加油，感谢你帮我找出代码上的问题，写完都没验证...
