### ISSUE TITLE
CER calculation

### ISSUE THREAD

**Issue by ZuoyunZheng** [Lornatang/CRNN-PyTorch#3]
Hi, thanks for the great work first and foremost!

I noticed that the accuracy calculation is not quite the CER needed. I was wondering if this is just a temporary fix or what does this:  `"".join(prediction_chars[0]) == target[0].lower()` mean?

**Comment by Lornatang** [comment]
Use CTC to decode: 
```python
_, prediction_chars = ctc_decode (output_log_probs, config.chars_dict)
if "".join(prediction_chars[0]) == target[0].lower():
      total_correct += 1
```

Determine whether the prediction char is equal the label
if true, total_correct add 1.
