### ISSUE TITLE
大佬您好，可以重新给一下谷歌云盘的链接吗，现在的失效了

### ISSUE THREAD

**Issue by Minsky520** [Lornatang/CRNN-PyTorch#5]

**Comment by Minsky520** [comment]
就是数据集部分的谷歌链接

**Comment by Lornatang** [comment]
谷歌云盘没空间了，发百度网盘链接给你吧。

链接：https://pan.baidu.com/s/1MlgQU1r2xn7hqsBeJ_cDBA?pwd=i0jw 
提取码：i0jw
