### ISSUE TITLE
训练时候找不到对应图片报错

### ISSUE THREAD

**Issue by Minsky520** [Lornatang/CRNN-PyTorch#6]
我使用了大佬在百度网盘中提供的MJSynth.zip数据集进行训练
![image](https://github.com/user-attachments/assets/4bb400a4-c970-4bd3-8b47-25a955f18e0f)
但是在训练过程中出现报错
![image](https://github.com/user-attachments/assets/61c011b0-fc5e-41fe-9318-cc22b6da82f7)
经过j检查发现数据集中并没有MJSynth/1730/361_HEREON_35880.jpg这个图片，请问大佬用的是哪个数据集训练的呢
![image](https://github.com/user-attachments/assets/842704db-2295-49aa-a9d0-d538afa9f5ac)
或者是
![image](https://github.com/user-attachments/assets/dfa2df2a-89b9-409e-84b5-be7b78c7b9c7)

**Comment by Lornatang** [comment]
MJSynth.zip训练。
有可能解压不完整，也有可能原始压缩包中该图片损坏，尝试清除后再运行一次

**Comment by Minsky520** [comment]
感谢您的回复，我正在尝试解决，顺便问一下大佬，在训练过程中
在独自使用3090服务器并且显存充足的情况下，程序正常速度运行一段时间后会间歇突然卡顿，并且再过一小段时间回复正常，重复发生，这是什么问题呀

**Comment by Lornatang** [comment]
可能是陷入了读取瓶颈，跟网速，机器CPU解码性能等有关系
